name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: docker://ianwalter/puppeteer@3.0.2-14.5
        with:
          args: yarn
      - name: Lint
        uses: docker://ianwalter/puppeteer@3.0.2-14.5
        with:
          args: yarn lint
      - name: Test
        uses: docker://ianwalter/puppeteer@3.0.2-14.5
        with:
          args: yarn test
